Repository tfcp68/yantrix, pull requests merged in 2024-05, with the labels that each got.

#52 Codegen features
  packages/codegen/src/codegens/JavaScriptCodegen.ts
  packages/codegen/src/codegens/TypeScriptCodegen.ts
  packages/codegen/src/codegens/index.ts
  packages/codegen/src/codegens/shared.ts
  packages/codegen/src/codegens/utils.ts
  packages/codegen/src/index.ts
  packages/codegen/src/types.ts
  packages/codegen/src/utils.ts
Labels: duplicate

#63 Feat/share expression types
  packages/yantrix-parser/src/__test__/fixtures/expressions.ts
  packages/yantrix-parser/src/__test__/utils/utils.ts
  packages/yantrix-parser/src/grammar/parserGrammar.jison
  packages/yantrix-parser/src/index.ts
  packages/yantrix-parser/src/types/expressions.ts
  packages/yantrix-parser/src/types/guards.ts
  packages/yantrix-parser/src/types/keyItem.ts
  packages/yantrix-parser/src/yantrixParser.ts
Labels: needs formatting

#55 Add test for keyitem parser
  packages/yantrix-parser/src/__test__/fixtures/expressions.ts
  packages/yantrix-parser/src/__test__/fixtures/keyItem.ts
  packages/yantrix-parser/src/__test__/keyItem.test.ts
  packages/yantrix-parser/src/__test__/utils/utils.ts
  packages/yantrix-parser/src/grammar/parserGrammar.jison
  packages/yantrix-parser/src/types/expressions.ts
  packages/yantrix-parser/src/yantrixParser.ts
Labels: enhancement, needs formatting

#64 Codegen improvement
  packages/codegen/__tests__/fixtures/saveGenerated.ts
  packages/codegen/src/codegens/TypeScriptCodegen.ts
  packages/codegen/src/codegens/index.ts
  packages/codegen/src/core/Codegen.ts
  packages/codegen/src/core/modules/JavaScript.ts
  packages/codegen/src/core/modules/TypeScript.ts
  packages/codegen/src/core/modules/index.ts
  packages/codegen/src/core/shared.ts
  packages/codegen/src/index.ts
  packages/codegen/src/types/common.ts
  packages/codegen/src/utils.ts
  packages/codegen/src/utils/utils.ts
  packages/yantrix-parser/package.json
  packages/yantrix-parser/src/types/expressions.ts
  packages/yantrix-parser/src/yantrixParser.ts
  pnpm-lock.yaml
Labels: needs formatting

#61 feat(codegen): properties to methods
  packages/codegen/src/core/modules/JavaScript.ts
  packages/codegen/src/index.ts
  packages/codegen/src/types/common.ts
Labels: needs formatting
